/*!
 * Less - middleware (adapted from the stylus middleware)
 *
 * Original Copyright(c) 2010 LearnBoost <dev@learnboost.com>
 * MIT Licensed
 */

var less = require('less'),
    fs = require('fs'),
    url = require('url'),
    basename = require('path').basename,
    dirname = require('path').dirname,
    mkdirp = require('mkdirp'),
    join = require('path').join;

// Import map
var imports = {};

/**
 * Return Connect middleware with the given `options`.
 *
 * Options:
 *
 *    `force`           Always re-compile
 *    `once`            Only re-compile the one time
 *    `debug`           Output debugging information
 *    `src`             Source directory used to find .less files
 *    `dest`            Destination directory used to output .css files
 *                      when undefined defaults to `src`.
 *    `compress`        Whether the output .css files should be compressed
 *    `optimization`    The desired value of the less optimization option (0, 1, or 2. 0 is default)
 *
 * Examples:
 *
 * Pass the middleware to Connect, grabbing .less files from this directory
 * and saving .css files to _./public_. Also supplying our custom `compile` function.
 *
 * Following that we have a `static` layer setup to serve the .css
 * files generated by Less.
 *
 *      var server = connect.createServer(
 *          less.middleware({
 *              src: __dirname + '/public',
 *              compress: true
 *          })
 *        , connect.static(__dirname + '/public')
 *      );
 *
 * @param {Object} options
 * @return {Function}
 * @api public
 */
module.exports = less.middleware = function(options){
  var regex = {
    handle: /\.css$/,
    compress: /(\.|-)min\.css$/
  };

  options = options || {};

  // Accept src/dest dir
  if ('string' == typeof options) {
    options = { src: options };
  }

  // Only log if in debug mode
  var log = function(key, val) {
    if(options.debug) console.error('  \033[90m%s :\033[0m \033[36m%s\033[0m', key, val);
  };

  //check imports for changes
  var checkImports = function(path, fn) {
    var nodes = imports[path];
    if (!nodes) return fn();
    if (!nodes.length) return fn();

    var pending = nodes.length
      , changed = [];
    console.log(nodes);
    nodes.forEach(function(imported){
      fs.stat(imported.path, function(err, stat) {
        // error or newer mtime
        if (err || !imported.mtime || stat.mtime > imported.mtime) {
          changed.push(imported.path);
        }
        --pending || fn(changed);
      });
    });
  }

  // Once option
  options.once = options.once || false;

  // Compress option
  options.compress = typeof options.compress === 'undefined' ? 'auto' : options.compress;

  // Optimization option
  options.optimization = options.optimization || 0;

  // Source dir required
  var src = options.src;
  if (!src) { throw new Error('less.middleware() requires "src" directory'); }

  // Default dest dir to source
  var dest = options.dest ? options.dest : src;

  // Default compile callback
  options.render = options.render || function(str, lessPath, cssPath, callback) {
    var parser = new less.Parser({
      paths: [dirname(lessPath)],
      filename: lessPath,
      optimization: options.optimization
    });

    parser.parse(str, function(err, tree) {
      var css = tree.toCSS({
        compress: (options.compress == 'auto' ? regex.compress.test(cssPath) : options.compress)
      });

      imports[lessPath] = tree.rules
        .filter(function(rule) {
          return rule.path;
        })
        .map(function(rule) {
          return {
            mtime : Date.now(),
            path : join(dirname(lessPath), rule.path)
          };
        });

      callback(err, css);
    });
  };

  // Middleware
  return function(req, res, next) {
    if ('GET' != req.method && 'HEAD' != req.method) { return next(); }

    var path = url.parse(req.url).pathname;

    // Only handle the matching files
    if (regex.handle.test(path)) {
      var cssPath = join(dest, path);
      var lessPath = join(src, (
        regex.compress.test(path)
        ? path.replace(regex.compress, '.less')
        : path.replace('.css', '.less'
      )));

      log('source', lessPath);
      log('dest', cssPath);

      // Ignore ENOENT to fall through as 404
      var error = function(err) {
        next('ENOENT' == err.code ? null : err);
      };

      // Compile to cssPath
      var compile = function() {
        log('read', lessPath);

        fs.readFile(lessPath, 'utf8', function(err, str){
          if (err) { return error(err); }

          delete imports[lessPath];

          options.render(str, lessPath, cssPath, function(err, css){
            if (err) { return next(err); }

            log('render', lessPath);

            // Store that it has been compiled
            mkdirp(dirname(cssPath), 0777, function(err){
              if (err) return error(err);
              fs.writeFile(cssPath, css, 'utf8', next);
            });
          });
        });
      };

      // Force
      if (options.force) { return compile(); }

      // Re-compile on server restart, disregarding
      // mtimes since we need to map imports
      if (!imports[lessPath]) { return compile(); }

      // Only check/recompile if it has not been done at before
      if (options.once && imports[lessPath]) { next(); return; }

      // Compare mtimes
      fs.stat(lessPath, function(err, lessStats){
        if (err) { return error(err); }

        fs.stat(cssPath, function(err, cssStats){
          // CSS has not been compiled, compile it!
          if (err) {
            if ('ENOENT' == err.code) {
              log('not found', cssPath);

              // No CSS file found in dest
              compile();
            } else {
              next(err);
            }
          } else if (lessStats.mtime > cssStats.mtime) {
            log('modified', cssPath);

            // Source has changed, compile it
            compile();
          } else {
            checkImports(lessPath, function(changed){
              if (options.debug && changed.length) {
                changed.forEach(function(path) {
                  log('modified import %s', path);
                });
              }
              changed.length ? compile() : next();
            });
          }
        });
      });
    } else {
      next();
    }
  };
};
